### ISSUE TITLE
Admin mockup page

### ISSUE THREAD

**Issue by ryanm73** [dorm-room-cook/dorm-room-cook#11]
Please do work for this task in a branch named issue-11.
Create a rough draft mockup page for admin privileges.

- [x]  Ability to search for posts / users
- [x]  Ability to filter through results
- [x]  Results shown

**Comment by joshuahartmann** [comment]
Made a base of what the admin page could look like, no real functionality right now. Definitely more to add such as additional filters and a cleaner look.
