### ISSUE TITLE
Create profiles / set defaults / add vendor profile edit page

### ISSUE THREAD

**Issue by ryanm73** [dorm-room-cook/dorm-room-cook#3]
Please do work for this task in a branch named issue-03

- [x] Admin profile will be by default only
- [x] Student profile - if the user selects student, only display student form items
- [ ] Vendor profile - if the user selects vendor, only display vendor form info
- [ ] If possible, minimize redundancy between the two versions of the form.
- [x] If it's too difficult, just create two separate forms (you can use modals if you want)

**Comment by mlr77** [comment]
Profile form completed as edit only.
