### ISSUE TITLE
Add-recipe-page

### ISSUE THREAD

**Issue by mlr77** [dorm-room-cook/dorm-room-cook#4]
Please do work for this task in a branch named issue-04.

This should be completed only after default recipe data is added
- [x]  Double check all required data is marked as required
- [x]  Conform to the json default recipe data to see what is needed
- [x]  Mark any issues you run into so we can adjust accordingly

**Comment by joshuahartmann** [comment]
created the basis of what this page could look like, forms don't work at the moment

**Comment by joshuahartmann** [comment]
recipe api should be working now
